### PR TITLE
correct FSAL subpackage descriptions

### PR DESCRIPTION
**Pull request by ktdreyer**
The ceph FSAL description was copied & pasted for all of the other FSAL sub-packages. Correct the descriptions for each FSAL subpackage to reflect the contents.

### CODE REVIEW

**Comment by ktdreyer** [comment]
@alimaredia , @kalebskeithley , mind merging this? We can cherry-pick to the xenial- and yakkety- branches.

**Comment by ktdreyer** [comment]
and zesty-

**Comment by alimaredia** [comment]
@ktdreyer line 113 in control needs to have xfs.conf not vfs.conf. 

https://github.com/nfs-ganesha/nfs-ganesha-debian/pull/6/files#diff-d837a1c17de0268bcea321239ddbed47R113

**Comment by ktdreyer** [comment]
Good catch @alimaredia , I've amended my commit to include that `vfs.conf` -> `xfs.conf` change.

**Comment by ktdreyer** [comment]
Thanks. Who should merge to the other distro branches?

**Pull request merged**
