### PR TITLE
Debian improvements

### PR DESCRIPTION
**Pull request by ryno83**
Some improvements to the Debian Packaging

### CODE REVIEW

**Comment by malahal** [comment]
nfs-ganesha-lock.service may not exist after https://review.gerrithub.io/#/c/377206/

**Comment by ryno83** [comment]
@malahal You are right ! but I wonder which approach should be used here. A different file for each distro or using CMakelists.txt like nfs-ganesha-config.service-in.cmake : https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/scripts/systemd/nfs-ganesha-config.service-in.cmake . What do you think ?

**Comment by malahal** [comment]
I see nfs-ganesha.service.el7 and nfs-ganesha.service.debian. I followed
this approach with nfs-ganesha-lock.service. We discussed this in our last
call, there wasn't much consensus whether we should follow split-file
approach or invent cmake variables to create distro specific file at build
time.

**Comment by ryno83** [comment]
IMO We should follow the split file approach like you does with the nfs-ganesha-lock. I will create a new PR for nfs-ganesha-lock.service.

**Pull request merged**
